name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: reviewdog/action-setup@v1
      - name: Test
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          go test -v ./... 2>&1 | reviewdog -f=go-test -reporter=github-check -name=test
      - name: Build examples
        run: go build ./example/...
